### ISSUE TITLE
Missing part from one page

### ISSUE THREAD

**Issue by pavletabata** [RaEmber/raember.github.io#1]
Nice analysis here : https://raember.github.io/2017/06/24/youtube_formats/

however, could you give a bit more detail, that seems to be missing from there ?

I've encountered the similar to this: https://stackoverflow.com/questions/65797052/

How such videos can be downloaded? youtube-dl handles those occasions.

**Comment by raember** [comment]
Hey there. First off: Thank you for even reading my posts. This github.io "blog" of mine was something I did 4 years ago and never continued. A lot of things happened in the meantime and I haven't pursued any expermients/research into the mechanics of youtube, so I'm not sure I can give you much information. I'm also studying hard for my upcoming exams and don't have the time to invest in such research atm.
That being said, please feel free to ask me specific questions - I will answer them as good as I can. What details are you interested in specifically?

**Comment by pavletabata** [comment]
thanks for response. 
Your analysis article (to view from the point of external observer person) has been very detailed and useful for me, and many thanks for that.  
well, i've been trying to find your observations about "signatureCipher" but i couldnt find. 
for example, there are videos json file (i.e. [this given example from stackoverflow](https://youtube.com/get_video_info?video_id=hT_AD630-gE) ) which does not contain the "url" parameter, and instead have "signatureCipher", where the given url doesn't work to download the video.
So, i wanted to find some info in your article, about how to download those videos, but couldnt find...

**Comment by raember** [comment]
Iirc I've never encountered that back then. I think there was always a `url` parameter included. I suspect this is something that got added later than back when I looked into it. Maybe it coincides with the DASH formats.
As for how to deal with that, I suggest you look at [`youtube-dl`](https://github.com/ytdl-org/youtube-dl) - you might get your answer there.

**Comment by pavletabata** [comment]
thanks..
